# Generated by Django 3.2.5 on 2021-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('write_date', models.DateField(verbose_name='date published')),
                ('date', models.CharField(default='oooo년 oo월 oo일', max_length=15)),
                ('body', models.TextField()),
            ],
        ),
    ]
