# Generated by Django 3.2.5 on 2021-08-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamjamapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_title', models.CharField(max_length=100)),
                ('bucket_date', models.CharField(default='oooo년 oo월 oo일', max_length=15)),
                ('bucket_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='diary_body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='diary_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='diary_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='write_date',
        ),
    ]
